// minSize  could be changed to small medium large
const config1 = {
  maxHeight: 500,
  rowStyle: 'zebra',
  minSize: 'small',
  headers: ['Athlete', 'Sport', 'Team'],
  data: [
    ['Kobe Bryant', 'Basketball', 'Lakers'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Lebron James', 'Basketball', 'Mavericks'],
    ['Mike Trout', 'Baseball', 'Mavericks'],
    ['Starlin Castro', 'Baseball', 'Mavericks'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Stephen Curry', 'Basketball', 'Warriors'],
    ['Tim Duncan', 'Basketball', 'Spirs'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Kobe Bryant', 'Basketball', 'Lakers'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Lebron James', 'Basketball', 'Mavericks'],
    ['Mike Trout', 'Baseball', 'Mavericks'],
    ['Kobe Bryant', 'Basketball', 'Lakers'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Lebron James', 'Basketball', 'Mavericks'],
    ['Mike Trout', 'Baseball', 'Mavericks'],
    ['Kobe Bryant', 'Basketball', 'Lakers'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Lebron James', 'Basketball', 'Mavericks'],
    ['Mike Trout', 'Baseball', 'Mavericks'],
    ['Kobe Bryant', 'Basketball', 'Lakers'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Lebron James', 'Basketball', 'Mavericks'],
    ['Mike Trout', 'Baseball', 'Mavericks'],
    ['Kobe Bryant', 'Basketball', 'Lakers'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Lebron James', 'Basketball', 'Mavericks'],
    ['Mike Trout', 'Baseball', 'Mavericks'],
    ['Kobe Bryant', 'Basketball', 'Lakers'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Lebron James', 'Basketball', 'Mavericks'],
    ['Mike Trout', 'Baseball', 'Mavericks'],
    ['Kobe Bryant', 'Basketball', 'Lakers'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Lebron James', 'Basketball', 'Mavericks'],
    ['Mike Trout', 'Baseball', 'Mavericks'],
    ['Kobe Bryant', 'Basketball', 'Lakers'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Lebron James', 'Basketball', 'Mavericks'],
    ['Mike Trout', 'Baseball', 'Mavericks'],
    ['Kobe Bryant', 'Basketball', 'Lakers'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Lebron James', 'Basketball', 'Mavericks'],
    ['Mike Trout', 'Baseball', 'Mavericks'],
    ['Kobe Bryant', 'Basketball', 'Lakers'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Lebron James', 'Basketball', 'Mavericks'],
    ['Mike Trout', 'Baseball', 'Mavericks'],
    ['Kobe Bryant', 'Basketball', 'Lakers'],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['Lebron James', 'Basketball', 'Mavericks'],
    ['Mike Trout', 'Baseball', 'Mavericks'],
  ],
};

const config2 = {
  maxHeight: 500,
  rowStyle: 'line',
  minSize: 'large',
  headers: ['Athlete', 'Sport', 'Team', 'Position', 'Championships', 'MVP'],
  data: [
    ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzkahahahahahahai', 'Basketball', 'Mavericks', 'PF', 1, 1],
       ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
       ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],   ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
       ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
       ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
       ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
       ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
       ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
       ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
       ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
       ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
       ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
       ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
    ]
    }

export {config1, config2}
