// minSize  could be changed to small medium large
const config1 = {
  maxHeight: 500,
  rowStyle: 'zebra',
  minSize: 'small',
  headers: ['ID', 'Athlete', 'Sport', 'Team'],
  data: [
    ['1', 'Kobe Bryant', 'Basketball', 'Lakers'],
    ['2', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['3', 'Lebron James', 'Basketball', 'Mavericks'],
    ['4', 'Mike Trout', 'Baseball', 'Mavericks'],
    ['5', 'Starlin Castro', 'Baseball', 'Mavericks'],
    ['6', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['7', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['8', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['9', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['10', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['11', 'Stephen Curry', 'Basketball', 'Warriors'],
    ['12', 'Tim Duncan', 'Basketball', 'Spirs'],
    ['13', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['14', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['15', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['16', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['17', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['18', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['19', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['20', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['21', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['22', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['23', 'Kobe Bryant', 'Basketball', 'Lakers'],
    ['24', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['25', 'Lebron James', 'Basketball', 'Mavericks'],
    ['26', 'Mike Trout', 'Baseball', 'Mavericks'],
    ['27', 'Kobe Bryant', 'Basketball', 'Lakers'],
    ['28', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['29', 'Lebron James', 'Basketball', 'Mavericks'],
    ['30', 'Mike Trout', 'Baseball', 'Mavericks'],
    ['31', 'Kobe Bryant', 'Basketball', 'Lakers'],
    ['32', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['33', 'Lebron James', 'Basketball', 'Mavericks'],
    ['34', 'Mike Trout', 'Baseball', 'Mavericks'],
    ['35', 'Kobe Bryant', 'Basketball', 'Lakers'],
    ['36', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['37', 'Lebron James', 'Basketball', 'Mavericks'],
    ['38', 'Mike Trout', 'Baseball', 'Mavericks'],
    ['39', 'Kobe Bryant', 'Basketball', 'Lakers'],
    ['40', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['41', 'Lebron James', 'Basketball', 'Mavericks'],
    ['42', 'Mike Trout', 'Baseball', 'Mavericks'],
    ['43', 'Kobe Bryant', 'Basketball', 'Lakers'],
    ['44', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['45', 'Lebron James', 'Basketball', 'Mavericks'],
    ['46', 'Mike Trout', 'Baseball', 'Mavericks'],
    ['47', 'Kobe Bryant', 'Basketball', 'Lakers'],
    ['48', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['49', 'Lebron James', 'Basketball', 'Mavericks'],
    ['50', 'Mike Trout', 'Baseball', 'Mavericks'],
    ['51', 'Kobe Bryant', 'Basketball', 'Lakers'],
    ['52', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['53', 'Lebron James', 'Basketball', 'Mavericks'],
    ['54', 'Mike Trout', 'Baseball', 'Mavericks'],
    ['55', 'Kobe Bryant', 'Basketball', 'Lakers'],
    ['56', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['57', 'Lebron James', 'Basketball', 'Mavericks'],
    ['58', 'Mike Trout', 'Baseball', 'Mavericks'],
    ['59', 'Kobe Bryant', 'Basketball', 'Lakers'],
    ['60', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['61', 'Lebron James', 'Basketball', 'Mavericks'],
    ['62', 'Mike Trout', 'Baseball', 'Mavericks'],
    ['63', 'Kobe Bryant', 'Basketball', 'Lakers'],
    ['64', 'Dirk Nowitzki', 'Basketball', 'Mavericks'],
    ['65', 'Lebron James', 'Basketball', 'Mavericks'],
    ['66', 'Mike Trout', 'Baseball', 'Mavericks'],
  ],
};

const config2 = {
  maxHeight: 500,
  rowStyle: 'line',
  minSize: 'large',
  headers: ['Athlete', 'Sport', 'Team', 'Position', 'Championships', 'MVP'],
  data: [
    ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzkahahahahahahai', 'Basketball', 'Mavericks', 'PF', 1, 1],
    ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
    ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
    ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
    ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
    ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
    ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
    ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
    ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
    ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
    ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
    ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
    ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
    ['Kobe Bryant', 'Basketball', 'Lakers', 'SG', '5', 1],
    ['Dirk Nowitzki', 'Basketball', 'Mavericks', 'PF', 1, 1],
  ],
};

export { config1, config2 };
