// @flow
const SCROLL_EMITTED = 'SCROLL_EMITTED';
const HEADER_REF = 'HEADER_REF';
const CHANGE_DENSITY = 'CHANGE_DENSITY';
const CHANGE_PAGINATION_AMT = 'CHANGE_PAGINATION_AMT';
const CHANGE_PAGE = 'CHANGE_PAGE';
const DATA_LOADED = 'DATA_LOADED';

export {
  SCROLL_EMITTED,
  HEADER_REF,
  CHANGE_DENSITY,
  CHANGE_PAGINATION_AMT,
  CHANGE_PAGE,
  DATA_LOADED,
};
